apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  MYSQL_HOST: {{ .Values.configmap.mysqlHost | quote }}
  MYSQL_DATABASE: {{ .Values.configmap.mysqlDatabase  | quote}}
  REDIS_HOST: {{ .Values.configmap.redisHost | quote }}
