apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskdb
  labels:
    app: flaskdb
spec:
  replicas: {{ .Values.db.replicas }}
  selector:
    matchLabels:
      app: flaskdb
  template:
    metadata:
      labels:
        app: flaskdb
    spec:
{{- if .Values.dockerregistry.enabled }}
      imagePullSecrets:
        - name: docker-registry-secret
{{- end }}
      containers:
      - name: flaskdb
        image: {{ .Values.db.image }}:{{ .Values.db.tag }}
        ports:
        - containerPort: {{ .Values.db.containerPort }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: MYSQL_PASSWORD
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: MYSQL_USER
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MYSQL_DATABASE
