apiVersion: v1
kind: Service
metadata:
  name: flask-app
spec:
  type: ClusterIP
  selector:
    app: flask-app
  ports:
    - port: {{ .Values.app.servicePort }}
      targetPort: {{ .Values.app.containerPort }}
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: phonebook-mysql
spec:
  type: ClusterIP
  selector:
    app: phonebook-mysql
  ports:
    - port: {{ .Values.db.servicePort }}
      targetPort: {{ .Values.db.containerPort }}
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: flask-redis
spec:
  type: ClusterIP
  selector:
    app: flask-redis
  ports:
    - port: {{ .Values.redis.servicePort }}
      targetPort: {{ .Values.redis.containerPort }}
      protocol: TCP